musicas_iniciais = [
    {"titulo": "Untitled Track 2", "artista": "Other Rock", "duracao": "5:15"},
    {"titulo": "Know Your Enemy", "artista": "Rage Against the Machine", "duracao": "4:56"},
    {"titulo": "Aerials", "artista": "System of a Down", "duracao": "2:39"},
    {"titulo": "The Heretic Anthem", "artista": "Slipknot", "duracao": "3:28"},
    {"titulo": "Re-Arranged", "artista": "Limp Bizkit", "duracao": "3:59"},
    {"titulo": "Untitled Track 8", "artista": "Korn", "duracao": "6:06"},
    {"titulo": "Until the End", "artista": "Other Rock", "duracao": "3:17"},
    {"titulo": "For Whom the Bell Tolls", "artista": "Metallica", "duracao": "3:19"},
    {"titulo": "Break Stuff", "artista": "Limp Bizkit", "duracao": "5:02"},
    {"titulo": "Untitled Track 13", "artista": "Disturbed", "duracao": "4:41"},
    {"titulo": "Points of Authority", "artista": "Linkin Park", "duracao": "6:25"},
    {"titulo": "Untitled Track 3", "artista": "Megadeth", "duracao": "4:13"},
    {"titulo": "Untitled Track 37", "artista": "Metallica", "duracao": "4:37"},
    {"titulo": "Untitled Track 25", "artista": "Slipknot", "duracao": "3:05"},
    {"titulo": "Behind Blue Eyes", "artista": "Limp Bizkit", "duracao": "3:25"},
    {"titulo": "Given Up", "artista": "Linkin Park", "duracao": "2:44"},
    {"titulo": "Countdown to Extinction", "artista": "Megadeth", "duracao": "5:38"},
    {"titulo": "Whiplash", "artista": "Metallica", "duracao": "5:57"},
    {"titulo": "Untitled Track 1", "artista": "Linkin Park", "duracao": "3:42"},
    {"titulo": "Set the World Afire", "artista": "Megadeth", "duracao": "4:13"},
    {"titulo": "Rust in Peace... Polaris", "artista": "Megadeth", "duracao": "5:38"},
    {"titulo": "Untitled Track 46", "artista": "System of a Down", "duracao": "6:21"},
    {"titulo": "Untitled Track 42", "artista": "Slipknot", "duracao": "5:46"},
    {"titulo": "Untitled Track 29", "artista": "Linkin Park", "duracao": "4:54"},
    {"titulo": "In the End", "artista": "Linkin Park", "duracao": "3:15"},
    {"titulo": "Untitled Track 9", "artista": "System of a Down", "duracao": "4:01"},
    {"titulo": "Untitled Track 11", "artista": "Korn", "duracao": "3:50"},
    {"titulo": "Shadow of the Day", "artista": "Linkin Park", "duracao": "4:00"},
    {"titulo": "Shoots and Ladders", "artista": "Korn", "duracao": "3:15"},
    {"titulo": "Good God", "artista": "Korn", "duracao": "6:18"},
    {"titulo": "Bleed It Out", "artista": "Linkin Park", "duracao": "6:17"},
    {"titulo": "Somewhere I Belong", "artista": "Linkin Park", "duracao": "6:09"},
    {"titulo": "Hemorrhage", "artista": "Other Rock", "duracao": "3:09"},
    {"titulo": "Untitled Track 35", "artista": "Korn", "duracao": "3:05"},
    {"titulo": "Untitled Track 22", "artista": "Korn", "duracao": "5:29"},
    {"titulo": "Untitled Track 40", "artista": "Korn", "duracao": "3:30"},
    {"titulo": "Rollin'", "artista": "Limp Bizkit", "duracao": "2:56"},
    {"titulo": "Holy Wars... The Punishment Due", "artista": "Megadeth", "duracao": "3:00"},
    {"titulo": "Last Resort", "artista": "Other Rock", "duracao": "3:47"},
    {"titulo": "Battery", "artista": "Metallica", "duracao": "4:23"},
    {"titulo": "Hypnotize", "artista": "System of a Down", "duracao": "4:22"},
    {"titulo": "Chop Suey!", "artista": "System of a Down", "duracao": "6:04"},
    {"titulo": "Untitled Track 4", "artista": "Linkin Park", "duracao": "6:03"},
    {"titulo": "Wake Up", "artista": "Rage Against the Machine", "duracao": "5:49"},
    {"titulo": "Untitled Track 39", "artista": "Megadeth", "duracao": "3:50"},
    {"titulo": "The Unforgiven", "artista": "Metallica", "duracao": "6:27"},
    {"titulo": "Runaway", "artista": "Linkin Park", "duracao": "4:22"},
    {"titulo": "Holier Than Thou", "artista": "Metallica", "duracao": "6:09"},
    {"titulo": "Passenger", "artista": "Deftones", "duracao": "4:02"},
    {"titulo": "Untitled Track 23", "artista": "Metallica", "duracao": "3:27"},
    {"titulo": "Untitled Track 30", "artista": "Deftones", "duracao": "4:17"},
    {"titulo": "Stupify", "artista": "Disturbed", "duracao": "3:21"},
    {"titulo": "Testify", "artista": "Rage Against the Machine", "duracao": "2:50"},
    {"titulo": "The Vengeful One", "artista": "Disturbed", "duracao": "3:22"},
    {"titulo": "The Sound of Silence", "artista": "Disturbed", "duracao": "4:04"},
    {"titulo": "Untitled Track 28", "artista": "Metallica", "duracao": "3:57"},
    {"titulo": "All Nightmare Long", "artista": "Metallica", "duracao": "3:31"},
    {"titulo": "Untitled Track 43", "artista": "Korn", "duracao": "3:39"},
    {"titulo": "Killing Is My Business", "artista": "Megadeth", "duracao": "5:41"},
    {"titulo": "Here to Stay", "artista": "Korn", "duracao": "6:13"},
    {"titulo": "Faith", "artista": "Limp Bizkit", "duracao": "2:41"},
    {"titulo": "I Stand Alone", "artista": "Other Rock", "duracao": "5:28"},
    {"titulo": "Untitled Track 34", "artista": "Korn", "duracao": "4:30"},
    {"titulo": "A Tout Le Monde", "artista": "Megadeth", "duracao": "4:05"},
    {"titulo": "Inside the Fire", "artista": "Disturbed", "duracao": "3:10"},
    {"titulo": "Another Way to Die", "artista": "Disturbed", "duracao": "3:39"},
    {"titulo": "Seek & Destroy", "artista": "Metallica", "duracao": "5:51"},
    {"titulo": "Before I Forget", "artista": "Slipknot", "duracao": "4:23"},
    {"titulo": "Nothing Else Matters", "artista": "Metallica", "duracao": "3:54"},
    {"titulo": "Twisted Transistor", "artista": "Korn", "duracao": "6:22"},
    {"titulo": "Tornado of Souls", "artista": "Megadeth", "duracao": "5:24"},
    {"titulo": "Untitled Track 17", "artista": "Limp Bizkit", "duracao": "5:26"},
    {"titulo": "My Generation", "artista": "Limp Bizkit", "duracao": "5:00"},
    {"titulo": "Nookie", "artista": "Limp Bizkit", "duracao": "6:16"},
    {"titulo": "Until It Sleeps", "artista": "Metallica", "duracao": "4:08"},
    {"titulo": "The Day That Never Comes", "artista": "Metallica", "duracao": "4:13"},
    {"titulo": "Edge of a Revolution", "artista": "Other Rock", "duracao": "3:05"},
    {"titulo": "Coming Undone", "artista": "Korn", "duracao": "4:10"},
    {"titulo": "Digital Bath", "artista": "Deftones", "duracao": "6:06"},
    {"titulo": "The Quiet Things That No One Ever Knows", "artista": "Other Rock", "duracao": "5:01"},
    {"titulo": "Untitled Track 32", "artista": "Deftones", "duracao": "4:19"},
    {"titulo": "Alone I Break", "artista": "Korn", "duracao": "5:48"},
    {"titulo": "Stricken", "artista": "Disturbed", "duracao": "6:19"},
    {"titulo": "Untitled Track 33", "artista": "Megadeth", "duracao": "2:52"},
    {"titulo": "Guerrilla Radio", "artista": "Rage Against the Machine", "duracao": "5:06"},
    {"titulo": "Take a Look Around", "artista": "Limp Bizkit", "duracao": "6:30"},
    {"titulo": "Untitled Track 16", "artista": "Disturbed", "duracao": "3:40"},
    {"titulo": "Question!", "artista": "System of a Down", "duracao": "6:22"},
    {"titulo": "...And Justice for All", "artista": "Metallica", "duracao": "2:32"},
    {"titulo": "Peace Sells", "artista": "Megadeth", "duracao": "5:47"},
    {"titulo": "Untitled Track 49", "artista": "Rage Against the Machine", "duracao": "2:33"},
    {"titulo": "Burn It Down", "artista": "Linkin Park", "duracao": "2:50"},
    {"titulo": "Mechanix", "artista": "Megadeth", "duracao": "6:24"},
    {"titulo": "Diamond Eyes", "artista": "Deftones", "duracao": "5:20"},
    {"titulo": "Bodies", "artista": "Other Rock", "duracao": "5:31"},
    {"titulo": "Change (In the House of Flies)", "artista": "Deftones", "duracao": "5:23"},
    {"titulo": "Untitled Track 47", "artista": "Korn", "duracao": "5:56"},
    {"titulo": "From the Inside", "artista": "Linkin Park", "duracao": "4:15"},
    {"titulo": "Did My Time", "artista": "Korn", "duracao": "6:29"},
    {"titulo": "Untitled Track 31", "artista": "Korn", "duracao": "3:02"},
    {"titulo": "Indestructible", "artista": "Disturbed", "duracao": "3:08"},
    {"titulo": "Wherever I May Roam", "artista": "Metallica", "duracao": "3:45"},
    {"titulo": "Untitled Track 6", "artista": "Linkin Park", "duracao": "2:35"},
    {"titulo": "Crawling", "artista": "Linkin Park", "duracao": "3:22"},
    {"titulo": "Vermilion", "artista": "Slipknot", "duracao": "5:41"},
    {"titulo": "Untitled Track 38", "artista": "Other Rock", "duracao": "4:27"},
    {"titulo": "Sulfur", "artista": "Slipknot", "duracao": "2:38"},
    {"titulo": "Untitled Track 27", "artista": "Korn", "duracao": "4:32"},
    {"titulo": "Rocket Skates", "artista": "Deftones", "duracao": "2:56"},
    {"titulo": "Untitled Track 21", "artista": "Other Rock", "duracao": "3:46"},
    {"titulo": "Prison Song", "artista": "System of a Down", "duracao": "2:37"},
    {"titulo": "Waiting for the End", "artista": "Linkin Park", "duracao": "4:57"},
    {"titulo": "Freak on a Leash", "artista": "Korn", "duracao": "5:26"},
    {"titulo": "Snuff", "artista": "Slipknot", "duracao": "6:27"},
    {"titulo": "Symphony of Destruction", "artista": "Megadeth", "duracao": "4:27"},
    {"titulo": "Untitled Track 7", "artista": "Korn", "duracao": "3:07"},
    {"titulo": "Down", "artista": "Other Rock", "duracao": "5:15"},
    {"titulo": "Numb", "artista": "Linkin Park", "duracao": "4:25"},
    {"titulo": "Psychosocial", "artista": "Slipknot", "duracao": "5:41"},
    {"titulo": "My Way", "artista": "Limp Bizkit", "duracao": "5:27"},
    {"titulo": "Lonely Day", "artista": "System of a Down", "duracao": "6:13"},
    {"titulo": "Harvester of Sorrow", "artista": "Metallica", "duracao": "3:19"},
    {"titulo": "Untitled Track 12", "artista": "Limp Bizkit", "duracao": "3:28"},
    {"titulo": "The Shortest Straw", "artista": "Metallica", "duracao": "5:14"},
    {"titulo": "Untitled Track 5", "artista": "Other Rock", "duracao": "5:14"},
    {"titulo": "Untitled Track 15", "artista": "Other Rock", "duracao": "5:37"},
    {"titulo": "Fade to Black", "artista": "Metallica", "duracao": "3:38"},
    {"titulo": "Leave Out All the Rest", "artista": "Linkin Park", "duracao": "5:34"},
    {"titulo": "New Divide", "artista": "Linkin Park", "duracao": "3:02"},
    {"titulo": "The Conjuring", "artista": "Megadeth", "duracao": "3:20"},
    {"titulo": "Wake Up Dead", "artista": "Megadeth", "duracao": "5:00"},
    {"titulo": "Untitled Track 48", "artista": "Linkin Park", "duracao": "5:43"},
    {"titulo": "Untitled Track 26", "artista": "Slipknot", "duracao": "6:26"},
    {"titulo": "Creeping Death", "artista": "Metallica", "duracao": "4:28"},
    {"titulo": "Bulls on Parade", "artista": "Rage Against the Machine", "duracao": "5:48"},
    {"titulo": "Welcome Home (Sanitarium)", "artista": "Metallica", "duracao": "3:39"},
    {"titulo": "The Call of Ktulu", "artista": "Metallica", "duracao": "5:29"},
    {"titulo": "Enter Sandman", "artista": "Metallica", "duracao": "2:55"},
    {"titulo": "Untitled Track 41", "artista": "Linkin Park", "duracao": "6:05"},
    {"titulo": "King Nothing", "artista": "Metallica", "duracao": "5:09"},
    {"titulo": "Skin o' My Teeth", "artista": "Megadeth", "duracao": "5:30"},
    {"titulo": "People = Shit", "artista": "Slipknot", "duracao": "4:30"},
    {"titulo": "Killing in the Name", "artista": "Rage Against the Machine", "duracao": "3:53"},
    {"titulo": "Untitled Track 24", "artista": "Linkin Park", "duracao": "3:33"},
    {"titulo": "B.Y.O.B.", "artista": "System of a Down", "duracao": "3:55"},
    {"titulo": "Blind", "artista": "Korn", "duracao": "3:52"},
    {"titulo": "Got the Life", "artista": "Korn", "duracao": "4:17"},
    {"titulo": "One", "artista": "Metallica", "duracao": "5:26"},
    {"titulo": "Stuck", "artista": "Limp Bizkit", "duracao": "4:40"},
    {"titulo": "Be Quiet and Drive (Far Away)", "artista": "Deftones", "duracao": "2:40"},
    {"titulo": "Boiler", "artista": "Limp Bizkit", "duracao": "2:54"},
    {"titulo": "Ride the Lightning", "artista": "Metallica", "duracao": "6:26"},
    {"titulo": "Down with the Sickness", "artista": "Disturbed", "duracao": "5:40"},
    {"titulo": "Blackened", "artista": "Metallica", "duracao": "5:18"},
    {"titulo": "Orion", "artista": "Metallica", "duracao": "3:12"},
    {"titulo": "Prayer", "artista": "Disturbed", "duracao": "3:51"},
    {"titulo": "Untitled Track 36", "artista": "Rage Against the Machine", "duracao": "3:30"},
    {"titulo": "Duality", "artista": "Slipknot", "duracao": "4:23"},
    {"titulo": "A.D.I.D.A.S.", "artista": "Korn", "duracao": "3:34"},
    {"titulo": "My Own Summer (Shove It)", "artista": "Deftones", "duracao": "5:50"},
    {"titulo": "Clown", "artista": "Korn", "duracao": "2:32"},
    {"titulo": "Untitled Track 45", "artista": "Other Rock", "duracao": "4:35"},
    {"titulo": "The Memory Remains", "artista": "Metallica", "duracao": "5:26"},
    {"titulo": "Untitled Track 19", "artista": "System of a Down", "duracao": "3:53"},
    {"titulo": "Spit It Out", "artista": "Slipknot", "duracao": "2:39"},
    {"titulo": "One Step Closer", "artista": "Linkin Park", "duracao": "3:05"},
    {"titulo": "Trust", "artista": "Megadeth", "duracao": "4:58"},
    {"titulo": "Fuel", "artista": "Metallica", "duracao": "3:53"},
    {"titulo": "Bombtrack", "artista": "Rage Against the Machine", "duracao": "3:39"},
    {"titulo": "Ten Thousand Fists", "artista": "Disturbed", "duracao": "2:54"},
    {"titulo": "Hangar 18", "artista": "Megadeth", "duracao": "3:25"},
    {"titulo": "Untitled Track 20", "artista": "Korn", "duracao": "6:15"},
    {"titulo": "Papercut", "artista": "Linkin Park", "duracao": "5:10"},
    {"titulo": "Untitled Track 52", "artista": "System of a Down", "duracao": "3:52"},
    {"titulo": "Untitled Track 14", "artista": "Other Rock", "duracao": "4:01"},
    {"titulo": "Sugar", "artista": "System of a Down", "duracao": "5:34"},
    {"titulo": "Sweating Bullets", "artista": "Megadeth", "duracao": "5:27"},
    {"titulo": "Make Me Bad", "artista": "Korn", "duracao": "5:07"},
    {"titulo": "Lost in the Echo", "artista": "Linkin Park", "duracao": "3:04"},
    {"titulo": "Spiders", "artista": "System of a Down", "duracao": "5:45"},
    {"titulo": "Untitled Track 51", "artista": "Megadeth", "duracao": "4:56"},
    {"titulo": "Faint", "artista": "Linkin Park", "duracao": "3:17"},
    {"titulo": "Untitled Track 18", "artista": "Metallica", "duracao": "6:07"},
    {"titulo": "In My Darkest Hour", "artista": "Megadeth", "duracao": "3:54"},
    {"titulo": "What I've Done", "artista": "Linkin Park", "duracao": "4:19"},
    {"titulo": "Untitled Track 50", "artista": "Disturbed", "duracao": "2:55"},
    {"titulo": "Falling Away from Me", "artista": "Korn", "duracao": "4:48"},
    {"titulo": "The Four Horsemen", "artista": "Metallica", "duracao": "5:12"},
    {"titulo": "Train of Consequences", "artista": "Megadeth", "duracao": "4:22"},
    {"titulo": "Untitled Track 10", "artista": "Other Rock", "duracao": "5:42"},
    {"titulo": "Wait and Bleed", "artista": "Slipknot", "duracao": "5:12"},
    {"titulo": "Minerva", "artista": "Deftones", "duracao": "3:26"},
    {"titulo": "Toxicity", "artista": "System of a Down", "duracao": "4:22"},
    {"titulo": "Master of Puppets", "artista": "Metallica", "duracao": "3:19"},
    {"titulo": "Breaking the Habit", "artista": "Linkin Park", "duracao": "2:42"},
    {"titulo": "Gold Cobra", "artista": "Limp Bizkit", "duracao": "5:05"},
    {"titulo": "Untitled Track 44", "artista": "Deftones", "duracao": "6:05"},
    {"titulo": "Swerve City", "artista": "Other Rock", "duracao": "6:05"},
    {"titulo": "Sad but True", "artista": "Metallica", "duracao": "6:24"},
    {"titulo": "Thoughtless", "artista": "Korn", "duracao": "5:55"},
]
